name: Lighthouse CI

on:
  repository_dispatch:
    types: [trigger_lighthouse_ci]
  push:
    branches:
      lighthouse-ci
jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.8.x

      - name: Run Lighthouse CI
        run: lhci autorun --collect.url=${{ github.event.client_payload.url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: Send report to API
        run: |
          REPORT_JSON=$(cat .lighthouseci/manifest.json)
          curl -X POST http://localhost:3000/api/receive-report \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d "{\"email\": \"${{ github.event.client_payload.email }}\", \"report\": $REPORT_JSON}"
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
