name: Lighthouse CI

on:
  repository_dispatch:
    types: [trigger_lighthouse_ci]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Collect Lighthouse results for mobile
        run: lhci collect --config=.lighthouserc.mobile.js
        env:
          LIGHTHOUSE_URL: ${{ github.event.client_payload.url }}

      - name: Upload Lighthouse results for mobile
        run: lhci upload --config=.lighthouserc.mobile.js

      - name: Collect Lighthouse results for desktop
        run: lhci collect --config=.lighthouserc.desktop.js
        env:
          LIGHTHOUSE_URL: ${{ github.event.client_payload.url }}

      - name: Upload Lighthouse results for desktop
        run: lhci upload --config=.lighthouserc.desktop.js

      - name: Assert results
        run: lhci assert

    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
